@echo off
echo Starting Server...
start "Fyers Server" python servermin.py
echo Waiting 5 seconds...
timeout /t 5
echo Starting Strategy Alerts...
start "Strategy Alerts" python strategy_alerts.py
echo Done.
